# Generated by Django 2.0.2 on 2023-10-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='creator',
            field=models.CharField(blank=True, default='ben', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='reviewer',
            field=models.CharField(blank=True, default='ben', max_length=20, null=True),
        ),
    ]
